# Generated by Django 3.0 on 2019-12-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_picker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Movie',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='text',
            new_name='title',
        ),
    ]
